scoreboard:
  lobby:
    enabled: true
    title: "&e&lSKYWARS"
    lines:
      - "&7Wins &8» &e%wins%"
      - ""
      - "&7Kills &8» &e%kills%"
      - ""
      - "&7Coins &8» &e%coins%"
      - ""
      - "&7GamesPlayed &8» &e%gamesPlayed%"
      -
      - "&ePlay.FalconMC.Online"
  game:
    waiting:
      enabled: true
      title: "&e&lSKYWARS"
      lines:
        - "&7Stats &8» &e%stats%"
        - ""
        - "&7Players &8» &e%playerCount%"
        - ""
        - "&7GamesPlayed &8» &e%gamesPlayed%"
        - ""
        - "&ePlay.FalconMC.Online"
    inGame:
      enabled: true
      title: "&e&lSKYWARS"
      lines:
        - "&7Kills &8» &e%kills%"
        - ""
        - "&7Alive &8» &e%aliveCount%"
        - ""
        - "&ePlay.FalconMC.Online"

coinsPerKill: 15

chestItems:
  normal:
    0:
      material: LEATHER_HELMET
      chance: 0.164
      minAmount: 1
      maxAmount: 1
    1:
      material: IRON_HELMET
      chance: 0.10
      minAmount: 1
      maxAmount: 1
    2:
      material: LEATHER_LEGGINGS
      chance: 0.64
      minAmount: 1
      maxAmount: 1
    3:
      material: IRON_LEGGINGS
      chance: 0.56
      minAmount: 1
      maxAmount: 1
    4:
      material: CHAINMAIL_LEGGINGS
      chance: 0.56
      minAmount: 1
      maxAmount: 1
    5:
      material: GOLD_LEGGINGS
      chance: 0.052
      minAmount: 1
      maxAmount: 1
    6:
      material: LEATHER_BOOTS
      chance: 0.152
      minAmount: 1
      maxAmount: 1
    7:
      material: IRON_BOOTS
      chance: 0.124
      minAmount: 1
      maxAmount: 1
    8:
      material: LEATHER_CHESTPLATE
      chance: 0.252
      minAmount: 1
      maxAmount: 1
    9:
      material: IRON_CHESTPLATE
      chance: 0.168
      minAmount: 1
      maxAmount: 1
    10:
      material: GOLD_CHESTPLATE
      chance: 0.108
      minAmount: 1
      maxAmount: 1
    11:
      material: STONE_SWORD
      chance: 0.432
      enchantments:
        DAMAGE_ALL: 1
      minAmount: 1
      maxAmount: 1
    12:
      material: STONE_SWORD
      chance: 0.408
      minAmount: 1
      maxAmount: 1
    13:
      material: IRON_SWORD
      chance: 0.228
      minAmount: 1
      maxAmount: 1
    14:
      material: FISHING_ROD
      chance: 0.228
      minAmount: 1
      maxAmount: 1
    15:
      material: BOW
      chance: 0.12
      minAmount: 1
      maxAmount: 1
    16:
      material: STONE_PICKAXE
      chance: 0.576
      minAmount: 1
      maxAmount: 1
    17:
      material: IRON_PICKAXE
      chance: 0.492
      minAmount: 1
      maxAmount: 1
    18:
      material: IRON_AXE
      chance: 0.084
      minAmount: 1
      maxAmount: 1
    19:
      material: WOOD
      chance: 0.90
      minAmount: 16
      maxAmount: 24
    20:
      material: STONE
      chance: 0.648
      minAmount: 16
      maxAmount: 24
    21:
      material: EGG
      chance: 0.54
      minAmount: 8
      maxAmount: 16
    22:
      material: SNOW_BALLS
      chance: 0.528
      minAmount: 8
      maxAmount: 8
    23:
      material: EXP_BOTTLE
      chance: 0.528
      minAmount: 8
      maxAmount: 16
    24:
      material: GOLDEN_APPLE
      chance: 0.12
      minAmount: 1
      maxAmount: 1
    25:
      material: WATER_BUCKET
      chance: 0.156
      minAmount: 1
      maxAmount: 1
    26:
      material: LAVA_BUCKET
      chance: 0.084
      minAmount: 1
      maxAmount: 1
    27:
      material: COOKED_BEEF
      chance: 1.0
      minAmount: 16
      maxAmount: 16


  middle:
    0:
      material: FISHING_ROD
      chance: 0.228
      minAmount: 1
      maxAmount: 1
    1:
      material: BOW
      chance: 0.12
      minAmount: 1
      maxAmount: 1
    2:
      material: STONE_PICKAXE
      chance: 0.576
      minAmount: 1
      maxAmount: 1
    3:
      material: IRON_PICKAXE
      chance: 0.492
      minAmount: 1
      maxAmount: 1
    4:
      material: IRON_AXE
      chance: 0.084
      minAmount: 1
      maxAmount: 1
    5:
      material: WOOD
      chance: 0.90
      minAmount: 16
      maxAmount: 24
    6:
      material: STONE
      chance: 0.648
      minAmount: 16
      maxAmount: 24
    7:
      material: EGG
      chance: 0.54
      minAmount: 8
      maxAmount: 16
    8:
      material: SNOW_BALLS
      chance: 0.528
      minAmount: 8
      maxAmount: 8
    9:
      material: EXP_BOTTLE
      chance: 0.528
      minAmount: 8
      maxAmount: 16
    10:
      material: GOLDEN_APPLE
      chance: 0.12
      minAmount: 1
      maxAmount: 1
    11:
      material: WATER_BUCKET
      chance: 0.156
      minAmount: 1
      maxAmount: 1
    12:
      material: LAVA_BUCKET
      chance: 0.084
      minAmount: 1
      maxAmount: 1
    13:
      material: COOKED_BEEF
      chance: 1.0
      minAmount: 16
      maxAmount: 16
    14:
      material: DIAMOND_SWORD
      chance: 0.1
      minAmount: 1
      maxAmount: 1
    15:
      material: DIAMOND_AXE
      chance: 0.1
      minAmount: 1
      maxAmount: 1
    16:
      material: DIAMOND_PICKAXE
      chance: 0.45
      minAmount: 1
      maxAmount: 1
    17:
      material: ENDER_PEARL
      chance: 0.2
      minAmount: 1
      maxAmount: 3
